FROM nginx:1.27-alpine

COPY index.html /usr/share/nginx/html/index.html
COPY styles.css /usr/share/nginx/html/styles.css
COPY script.js /usr/share/nginx/html/script.js
COPY og-image.svg /usr/share/nginx/html/og-image.svg
COPY og-image.png /usr/share/nginx/html/og-image.png

EXPOSE 80
